name: ExpenseTracker
options:
  minimumXcodeGenVersion: 2.35.0
  deploymentTarget:
    iOS: 16.0
packages:
  SQLite:
    url: https://github.com/stephencelis/SQLite.swift
    from: 0.14.1
targets:
  ExpenseTracker:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: App
      - path: Models
      - path: Services
      - path: Views
      - path: Resources
        type: folder
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.vineeth.expensetracker.ios
      DEVELOPMENT_TEAM: ""
      SWIFT_VERSION: 5.0
      INFOPLIST_FILE: App/Info.plist
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: 1.0
    dependencies:
      - package: SQLite
        product: SQLite

